const BusStops = ["Academia de Polícia",
"Acesso CPTM 2",
"Acesso CPTM I",
"Acesso São Remo",
"Acesso Vl. Indiana",
"Bancos",
"Biblioteca Brasiliana",
"Biênio",
"Biociências I",
"Biociências II",
"Biomédicas",
"Biomédicas III",
"Butantan",
"CEPAM",
"Civil",
"COPESP",
"CRUSP",
"Cultura Japonesa",
"ECA",
"Educação",
"Educação Física I",
"Educação Física II",
"Eletrotécnica",
"Farmácia e Química",
"FAU I",
"FAU II",
"FEA",
"Física",
"Geociências",
"Hidráulica",
"História e Geografia",
"Hospital Universitário",
"IAG",
"Inova USP",
"IPEN",
"IPT",
"Letras",
"MAE",
"Mecânica",
"Metalurgia",
"Metrô Butantã",
"Oceanográfico",
"Odontologia",
"Paço das Artes",
"Portaria II",
"Portaria III",
"Praça do Relógio",
"Prefeitura I",
"Prefeitura II",
"Prefeitura/Física",
"Psicologia I",
"Psicologia II",
"Raia Olímpica",
"Reitoria",
"Rua do Lago",
"Terminal de Ônibus Urbano"
]

export default BusStops;